workshops-info-list:
  workshops:
    manchester:
      name: "Manchester"
      url: "http://localhost:9004/"
      carTypes: "Passenger car,Truck"
      address: "14 Bury New Rd"
    london:
      name: "London"
      url: "http://localhost:9003/"
      carTypes: "Passenger car"
      address: "1A Gunton Rd"